MERCHANTS = [
    "Amazon",
    "Flipkart",
    "Myntra",
    "Ajio",
    "Reliance Digital",
    "Croma",
    "Swiggy",
    "Zomato",
    "Uber",
    "Ola",
    "BookMyShow",
    "BigBasket",
    "Blinkit",
    "DMart",
    "Starbucks",
    "Domino's",
    "KFC",
    "McDonald's",
    "Apollo Pharmacy",
    "IRCTC"
]